In [2]:


#importing libraries

import pandas as pd
import numpy as np

# uploading the file from the local drive

#candidate = pd.read_csv('/home/vishal/Documents/demo/data/candidate_data.csv')
job = pd.read_csv('/home/vishal/Documents/demo/data/job_data.csv')


job.head()



job_id      job_title  company_name  \
0  698bd881-1f62-4b8d-b4bf-b33b1eb1cfc1    Storekeeper  Amul company   
1  ceff9105-dfc6-4981-baae-6074bd8e77a8    Storekeeper  Amul company   
2  055b2d95-83ae-4050-a191-b09af946f938    Storekeeper  Amul company   
3  760f6fdb-0c3b-44c1-8332-e4a77b00ac54  first testing     first job   
4  9dacfc3a-b36c-416e-9125-199e2123518c      ड्रायव्हर  Tata company   

                                     job_description  \
0  <p>URGENT REQUIRED MALE &amp; FEMALE NEW STAFF...   
1  <p>URGENT REQUIRED MALE &amp; FEMALE NEW STAFF...   
2  <p>URGENT REQUIRED MALE &amp; FEMALE NEW STAFF...   
3                                     <p>testing</p>   
4                                                NaN   

                      created_at                    modified_at  \
0  2022-06-12 04:56:32.569 +0530  2022-06-26 06:25:23.123 +0530   
1  2022-06-12 04:57:34.633 +0530  2022-06-26 06:25:25.427 +0530   
2  2022-06-12 04:58:37.067 +0530  2022-06-26 06:25:31.386 +0530   
3  2022-07-02 17:47:19.447 +0530  2022-07-02 18:20:40.471 +0530   
4  2021-10-13 21:20:01.642 +0530  2021-10-16 14:48:49.491 +0530   

                     expiry_date  number_of_openings           education  \
0  2022-07-12 04:56:33.005 +0530                23.0           10th Pass   
1  2022-07-12 04:57:35.021 +0530                22.0           10th Pass   
2  2022-07-12 04:58:37.482 +0530                14.0           10th Pass   
3  2022-08-01 17:47:19.905 +0530                 2.0  8th Class or Below   
4  2021-11-12 21:20:01.642 +0530                 NaN           10th Pass   

  experience                        city          state  \
0    Fresher                      Ranchi      Jharkhand   
1    Fresher         Dhanbad (Jharkhand)      Jharkhand   
2    Fresher  Jamshedpur (East Singhbum)      Jharkhand   
3    Fresher                        Agra  Uttar Pradesh   
4    3-5 yrs                        Pune    Maharashtra   

                  salary                      trade type_of_work  
0  Rs. 10000 to Rs.15000  Food Production (General)    Full Time  
1  Rs. 10000 to Rs.15000  Food Production (General)    Full Time  
2  Rs. 10000 to Rs.15000  Food Production (General)    Full Time  
3     Less than Rs.10000              AC Technician    Full Time  
4  Rs. 15001 to Rs.25000                    Drivers    Full Time

In [3]:


# Listing out all the columns that are present in the data set.

list(job) 



['job_id',
 'job_title',
 'company_name',
 'job_description',
 'created_at',
 'modified_at',
 'expiry_date',
 'number_of_openings',
 'education',
 'experience',
 'city',
 'state',
 'salary',
 'trade',
 'type_of_work']

In [4]:

print(job.shape)
job.isnull().sum()


(3850, 15)


job_id                 0
job_title              2
company_name           1
job_description       94
created_at             0
modified_at            0
expiry_date            0
number_of_openings    90
education              0
experience             0
city                   0
state                  0
salary                 0
trade                  0
type_of_work           0
dtype: int64

In [5]:
job = job.dropna()
job.isnull().sum()

job_id                0
job_title             0
company_name          0
job_description       0
created_at            0
modified_at           0
expiry_date           0
number_of_openings    0
education             0
experience            0
city                  0
state                 0
salary                0
trade                 0
type_of_work          0
dtype: int64

In [6]:
#subsetting only needed columns and not considering the columns that are not necessary
cols = list(['job_id']+['company_name']+['job_title']+['trade']+ ['education']+['city']+['type_of_work']+['experience']+['salary'])
final_jobs =job[cols]
final_jobs.columns = ['job_id','company_name', 'job_title', 'trade', 'education','city', 'type_of_work','experience','salary']
final_jobs.head() 

job_id       company_name      job_title  \
0  698bd881-1f62-4b8d-b4bf-b33b1eb1cfc1       Amul company    Storekeeper   
1  ceff9105-dfc6-4981-baae-6074bd8e77a8       Amul company    Storekeeper   
2  055b2d95-83ae-4050-a191-b09af946f938       Amul company    Storekeeper   
3  760f6fdb-0c3b-44c1-8332-e4a77b00ac54          first job  first testing   
5  6f60b4d0-01c8-4e0d-9026-b5ff67cae327  Meksa Enterprises   Delivery Boy   

                       trade           education                        city  \
0  Food Production (General)           10th Pass                      Ranchi   
1  Food Production (General)           10th Pass         Dhanbad (Jharkhand)   
2  Food Production (General)           10th Pass  Jamshedpur (East Singhbum)   
3              AC Technician  8th Class or Below                        Agra   
5         Delivery Executive           10th Pass                       Delhi   

  type_of_work experience                 salary  
0    Full Time    Fresher  Rs. 10000 to Rs.15000  
1    Full Time    Fresher  Rs. 10000 to Rs.15000  
2    Full Time    Fresher  Rs. 10000 to Rs.15000  
3    Full Time    Fresher     Less than Rs.10000  
5    Full Time    Fresher  Rs. 10000 to Rs.15000

# corpus

In [7]:
final_jobs["trade_education_city_type_of_work_experience"] = final_jobs["trade"].map(str) + " " + final_jobs["education"] +" "+ final_jobs["city"]+ " "+final_jobs['type_of_work']+" "+final_jobs['experience']
final_jobs.trade_education_city_type_of_work_experience.head()

/snap/jupyter/6/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


0    Food Production (General) 10th Pass Ranchi Ful...
1    Food Production (General) 10th Pass Dhanbad (J...
2    Food Production (General) 10th Pass Jamshedpur...
3    AC Technician 8th Class or Below Agra Full Tim...
5    Delivery Executive 10th Pass Delhi Full Time F...
Name: trade_education_city_type_of_work_experience, dtype: object

In [8]:
import re
def cleanJob(jobText):
    jobText = re.sub('http\S+\s*', ' ', jobText)  # remove URl
    jobText = re.sub('RT|cc', ' ', jobText)  # remove RT and cc
    jobText = re.sub('#\S+', '', jobText)  # remove hashtags
    jobText = re.sub('@\S+', '  ', jobText)  # remove mentions
    jobText = re.sub('[%s]' % re.escape("""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""), ' ', jobText)  # remove punctuations
    jobText = re.sub(r'[^\x00-\x7f]',r' ', jobText) 
    jobText = re.sub('\s+', ' ', jobText)  # remove extra whitespace
    return jobText

In [9]:
final_jobs["cleaned_job"] = final_jobs.trade_education_city_type_of_work_experience.apply(lambda x: cleanJob(x))
print (final_jobs["cleaned_job"])

0       Food Production General 10th Pass Ranchi Full ...
1       Food Production General 10th Pass Dhanbad Jhar...
2       Food Production General 10th Pass Jamshedpur E...
3       AC Technician 8th Class or Below Agra Full Tim...
5       Delivery Executive 10th Pass Delhi Full Time F...
                              ...                        
3845    Automotive Fitter 8th Class or Below Noida Ful...
3846    Automotive Fitter 8th Class or Below Noida Ful...
3847    Automotive Fitter 8th Class or Below Noida Ful...
3848    Automotive Fitter 8th Class or Below Noida Ful...
3849    Automotive Fitter 8th Class or Below Noida Ful...
Name: cleaned_job, Length: 3683, dtype: object


/snap/jupyter/6/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [10]:


#converting all the characeters to lower case
final_jobs['cleaned_job'] = final_jobs['cleaned_job'].str.lower() 
final_jobs.cleaned_job.head()



/snap/jupyter/6/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


0    food production general 10th pass ranchi full ...
1    food production general 10th pass dhanbad jhar...
2    food production general 10th pass jamshedpur e...
3    ac technician 8th class or below agra full tim...
5    delivery executive 10th pass delhi full time f...
Name: cleaned_job, dtype: object

In [11]:
final_all = final_jobs[['job_id', 'cleaned_job']]
# renaming the column name as it seemed a bit complicated
final_all = final_jobs[['job_id', 'cleaned_job']]
final_all = final_all.fillna(" ")

final_all.head()

job_id  \
0  698bd881-1f62-4b8d-b4bf-b33b1eb1cfc1   
1  ceff9105-dfc6-4981-baae-6074bd8e77a8   
2  055b2d95-83ae-4050-a191-b09af946f938   
3  760f6fdb-0c3b-44c1-8332-e4a77b00ac54   
5  6f60b4d0-01c8-4e0d-9026-b5ff67cae327   

                                         cleaned_job  
0  food production general 10th pass ranchi full ...  
1  food production general 10th pass dhanbad jhar...  
2  food production general 10th pass jamshedpur e...  
3  ac technician 8th class or below agra full tim...  
5  delivery executive 10th pass delhi full time f...

In [12]:
print(final_all.head(1))


                                 job_id  \
0  698bd881-1f62-4b8d-b4bf-b33b1eb1cfc1   

                                         cleaned_job  
0  food production general 10th pass ranchi full ...  


# NLTK stands for Natural Languague Toolkit¶

In [13]:
cleaned_job = final_all['cleaned_job']
#removing stopwords and applying potter stemming
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
stemmer =  PorterStemmer()
stop = stopwords.words('english')
only_text = cleaned_job.apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
only_text.head()


0    food production general 10th pass ranchi full ...
1    food production general 10th pass dhanbad jhar...
2    food production general 10th pass jamshedpur e...
3       ac technician 8th class agra full time fresher
5    delivery executive 10th pass delhi full time f...
Name: cleaned_job, dtype: object

In [14]:


only_text = only_text.apply(lambda x : filter(None,x.split(" ")))
print(only_text.head())



0    <filter object at 0x7fad5953ed68>
1    <filter object at 0x7fad4b852860>
2    <filter object at 0x7fad4b852c18>
3    <filter object at 0x7fad4b852e10>
5    <filter object at 0x7fad4b852fd0>
Name: cleaned_job, dtype: object


In [15]:
only_text = only_text.apply(lambda x : [stemmer.stem(y) for y in x])
print(only_text.head())

0    [food, product, gener, 10th, pass, ranchi, ful...
1    [food, product, gener, 10th, pass, dhanbad, jh...
2    [food, product, gener, 10th, pass, jamshedpur,...
3    [ac, technician, 8th, class, agra, full, time,...
5    [deliveri, execut, 10th, pass, delhi, full, ti...
Name: cleaned_job, dtype: object


In [16]:


only_text = only_text.apply(lambda x : " ".join(x))
print(only_text.head())



0    food product gener 10th pass ranchi full time ...
1    food product gener 10th pass dhanbad jharkhand...
2    food product gener 10th pass jamshedpur east s...
3       ac technician 8th class agra full time fresher
5    deliveri execut 10th pass delhi full time fresher
Name: cleaned_job, dtype: object


In [17]:


#adding the featured column back to pandas
final_all['text']= only_text
# As we have added a new column by performing all the operations using lambda function, we are removing the unnecessary column
#final_all = final_all.drop("pos_com_city_empType_jobDesc", 1)

list(final_all)
final_all.head()



job_id  \
0  698bd881-1f62-4b8d-b4bf-b33b1eb1cfc1   
1  ceff9105-dfc6-4981-baae-6074bd8e77a8   
2  055b2d95-83ae-4050-a191-b09af946f938   
3  760f6fdb-0c3b-44c1-8332-e4a77b00ac54   
5  6f60b4d0-01c8-4e0d-9026-b5ff67cae327   

                                         cleaned_job  \
0  food production general 10th pass ranchi full ...   
1  food production general 10th pass dhanbad jhar...   
2  food production general 10th pass jamshedpur e...   
3  ac technician 8th class or below agra full tim...   
5  delivery executive 10th pass delhi full time f...   

                                                text  
0  food product gener 10th pass ranchi full time ...  
1  food product gener 10th pass dhanbad jharkhand...  
2  food product gener 10th pass jamshedpur east s...  
3     ac technician 8th class agra full time fresher  
5  deliveri execut 10th pass delhi full time fresher

In [18]:


# in order to save this file for a backup
final_all.to_csv("job_data.csv", index=True)



# TF-IDF ( Term Frequency - Inverse Document Frequency )

In [19]:
#initializing tfidf vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
#from sklearn.feature_extraction.text import CountVectorizer

tfidf_vectorizer = TfidfVectorizer()

tfidf_jobid = tfidf_vectorizer.fit_transform((final_all['text'])) #fitting and transforming the vector
tfidf_jobid

<3683x478 sparse matrix of type '<class 'numpy.float64'>'
	with 28846 stored elements in Compressed Sparse Row format>

# User query Corpus

In [20]:
# First reading my resume csv
candidate = pd.read_csv('/home/vishal/Documents/demo/data/candidate_data.csv')
candidate.head()

candidate_id                       name  \
0  2655f723-d24f-428c-a860-6788389e64ad         Nitin kumar sharma   
1  bc4d77ca-a201-4a84-a954-99fbd99c58c9            Md Aslam Ansari   
2  33c55193-9acc-4356-8219-326e10f8b930                     vishal   
3  aa14cd53-6d8a-4b29-a9a4-6b7f8f4611ed                   DEVENDER   
4  91ae7262-49c2-4e71-ab4b-26e5eaed1049  Prashant Vasudeo Dhongade   

                      created_at                      update_at       city  \
0  2021-08-15 13:46:46.625 +0530  2021-08-15 13:50:17.096 +0530  Ghaziabad   
1  2022-07-06 09:29:27.175 +0530  2022-07-07 13:08:42.776 +0530    Katihar   
2  2022-09-08 22:29:44.206 +0530  2022-09-12 11:47:41.566 +0530      Alwar   
3  2021-10-02 05:22:19.649 +0530  2021-10-02 06:06:55.440 +0530      Delhi   
4  2021-09-28 19:24:14.827 +0530  2021-09-28 19:31:58.006 +0530     Nagpur   

           state                     trade           education  \
0  Uttar Pradesh               Electrician             Diploma   
1          Bihar                    Mining  8th Class or Below   
2      Rajasthan                 Carpenter                 ITI   
3          Delhi                   Drivers           10th Pass   
4    Maharashtra  Multi Skilled Technician             Diploma   

           current_salary         expected_salary experience type_of_work  
0   Rs. 15001 to Rs.25000   Rs. 15001 to Rs.25000    3-5 yrs    Full Time  
1   Rs. 10000 to Rs.15000   Rs. 10000 to Rs.15000    0-2 Yrs    Part Time  
2  Rs. 25001 to Rs. 50000     More Than Rs. 50000    0-2 Yrs    Full Time  
3   Rs. 15001 to Rs.25000   Rs. 15001 to Rs.25000    10+ yrs    Full Time  
4   Rs. 15001 to Rs.25000  Rs. 25001 to Rs. 50000    3-5 yrs    Full Time

In [21]:
#subsetting only needed columns and not considering the columns that are not necessary
cols = list(['candidate_id']+['trade']+ ['education']+['city']+['type_of_work']+['experience']+['expected_salary'])
final_candidate =candidate[cols]
final_candidate.columns = ['candidate_id', 'trade', 'education','city', 'type_of_work','experience','expected_salary']
final_candidate.head() 

candidate_id                     trade  \
0  2655f723-d24f-428c-a860-6788389e64ad               Electrician   
1  bc4d77ca-a201-4a84-a954-99fbd99c58c9                    Mining   
2  33c55193-9acc-4356-8219-326e10f8b930                 Carpenter   
3  aa14cd53-6d8a-4b29-a9a4-6b7f8f4611ed                   Drivers   
4  91ae7262-49c2-4e71-ab4b-26e5eaed1049  Multi Skilled Technician   

            education       city type_of_work experience  \
0             Diploma  Ghaziabad    Full Time    3-5 yrs   
1  8th Class or Below    Katihar    Part Time    0-2 Yrs   
2                 ITI      Alwar    Full Time    0-2 Yrs   
3           10th Pass      Delhi    Full Time    10+ yrs   
4             Diploma     Nagpur    Full Time    3-5 yrs   

          expected_salary  
0   Rs. 15001 to Rs.25000  
1   Rs. 10000 to Rs.15000  
2     More Than Rs. 50000  
3   Rs. 15001 to Rs.25000  
4  Rs. 25001 to Rs. 50000

In [22]:

# checking for the null values again.
final_candidate.isnull().sum()



candidate_id       0
trade              0
education          0
city               0
type_of_work       0
experience         0
expected_salary    0
dtype: int64

In [23]:
df = final_candidate.dropna()

In [24]:
final_candidate["trade_education_city_type_of_work_experience"] = final_candidate["trade"].map(str) + " " + final_candidate["education"] +" "+ final_candidate["city"]+ " "+final_candidate['type_of_work']+" "+final_candidate['experience']
final_candidate.trade_education_city_type_of_work_experience.head()

/snap/jupyter/6/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


0      Electrician Diploma Ghaziabad Full Time 3-5 yrs
1    Mining 8th Class or Below Katihar Part Time 0-...
2                Carpenter ITI Alwar Full Time 0-2 Yrs
3            Drivers 10th Pass Delhi Full Time 10+ yrs
4    Multi Skilled Technician Diploma Nagpur Full T...
Name: trade_education_city_type_of_work_experience, dtype: object

In [25]:
final_candidate["cleaned_candidate"] = final_candidate.trade_education_city_type_of_work_experience.apply(lambda x: cleanJob(x))
print(final_candidate["cleaned_candidate"])

0          Electrician Diploma Ghaziabad Full Time 3 5 yrs
1        Mining 8th Class or Below Katihar Part Time 0 ...
2                    Carpenter ITI Alwar Full Time 0 2 Yrs
3                 Drivers 10th Pass Delhi Full Time 10 yrs
4        Multi Skilled Technician Diploma Nagpur Full T...
                               ...                        
40609    Drivers 8th Class or Below Agar Malwa Full Tim...
40610        Welder 12th pass Allahabad Full Time 5 10 yrs
40611          Waiter 10th Pass Dehradun Full Time Fresher
40612    RO Technicians 10th Pass Sitamarhi Contractual...
40613    RO Technicians Graduate Sitamarhi Contractual ...
Name: cleaned_candidate, Length: 40614, dtype: object


/snap/jupyter/6/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [26]:
final_candidate['cleaned_candidate'] = final_candidate['cleaned_candidate'].str.lower()
final_candidate.head()

/snap/jupyter/6/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


candidate_id                     trade  \
0  2655f723-d24f-428c-a860-6788389e64ad               Electrician   
1  bc4d77ca-a201-4a84-a954-99fbd99c58c9                    Mining   
2  33c55193-9acc-4356-8219-326e10f8b930                 Carpenter   
3  aa14cd53-6d8a-4b29-a9a4-6b7f8f4611ed                   Drivers   
4  91ae7262-49c2-4e71-ab4b-26e5eaed1049  Multi Skilled Technician   

            education       city type_of_work experience  \
0             Diploma  Ghaziabad    Full Time    3-5 yrs   
1  8th Class or Below    Katihar    Part Time    0-2 Yrs   
2                 ITI      Alwar    Full Time    0-2 Yrs   
3           10th Pass      Delhi    Full Time    10+ yrs   
4             Diploma     Nagpur    Full Time    3-5 yrs   

          expected_salary       trade_education_city_type_of_work_experience  \
0   Rs. 15001 to Rs.25000    Electrician Diploma Ghaziabad Full Time 3-5 yrs   
1   Rs. 10000 to Rs.15000  Mining 8th Class or Below Katihar Part Time 0-...   
2     More Than Rs. 50000              Carpenter ITI Alwar Full Time 0-2 Yrs   
3   Rs. 15001 to Rs.25000          Drivers 10th Pass Delhi Full Time 10+ yrs   
4  Rs. 25001 to Rs. 50000  Multi Skilled Technician Diploma Nagpur Full T...   

                                   cleaned_candidate  
0    electrician diploma ghaziabad full time 3 5 yrs  
1  mining 8th class or below katihar part time 0 ...  
2              carpenter iti alwar full time 0 2 yrs  
3           drivers 10th pass delhi full time 10 yrs  
4  multi skilled technician diploma nagpur full t...

In [35]:
final_candidate=final_candidate.loc[:,['candidate_id','cleaned_candidate']]
final_candidate.head()

candidate_id  \
0  2655f723-d24f-428c-a860-6788389e64ad   
1  bc4d77ca-a201-4a84-a954-99fbd99c58c9   
2  33c55193-9acc-4356-8219-326e10f8b930   
3  aa14cd53-6d8a-4b29-a9a4-6b7f8f4611ed   
4  91ae7262-49c2-4e71-ab4b-26e5eaed1049   

                                   cleaned_candidate  
0    electrician diploma ghaziabad full time 3 5 yrs  
1  mining 8th class or below katihar part time 0 ...  
2              carpenter iti alwar full time 0 2 yrs  
3           drivers 10th pass delhi full time 10 yrs  
4  multi skilled technician diploma nagpur full t...

In [36]:
import numpy as np

#taking a user
u = 'bc4d77ca-a201-4a84-a954-99fbd99c58c9'
index = np.where(final_candidate['candidate_id'] == u)[0][0]
user_q = final_candidate.iloc[[index]]
user_q



candidate_id  \
1  bc4d77ca-a201-4a84-a954-99fbd99c58c9   

                                   cleaned_candidate  
1  mining 8th class or below katihar part time 0 ...

# Using vector space model ( Cosine similarity )¶

In [39]:
#creating tf-idf of user query and computing cosine similarity of user with job corpus
from sklearn.metrics.pairwise import cosine_similarity
candidate_tfidf = tfidf_vectorizer.transform(user_q['cleaned_candidate'])

#job_tfidf from above
tfidf_jobid

output = map(lambda x: cosine_similarity(candidate_tfidf, x),tfidf_jobid)
output

In [40]:
output2 = list(output)
output2

[array([[0.01319956]]),
 array([[0.0114342]]),
 array([[0.01038802]]),
 array([[0.15058489]]),
 array([[0.01976949]]),
 array([[0.12812704]]),
 array([[0.14544603]]),
 array([[0.01214175]]),
 array([[0.01220914]]),
 array([[0.01357061]]),
 array([[0.01268802]]),
 array([[0.19848719]]),
 array([[0.01332157]]),
 array([[0.01907751]]),
 array([[0.01521572]]),
 array([[0.01386543]]),
 array([[0.01463134]]),
 array([[0.01425803]]),
 array([[0.01412681]]),
 array([[0.01602558]]),
 array([[0.14573635]]),
 array([[0.01743605]]),
 array([[0.00920094]]),
 array([[0.0138968]]),
 array([[0.01567076]]),
 array([[0.]]),
 array([[0.14102217]]),
 array([[0.13039934]]),
 array([[0.12266526]]),
 array([[0.01598997]]),
 array([[0.20704019]]),
 array([[0.01360787]]),
 array([[0.17713694]]),
 array([[0.0112108]]),
 array([[0.01617487]]),
 array([[0.01070289]]),
 array([[0.01298426]]),
 array([[0.01690279]]),
 array([[0.01539575]]),
 array([[0.01675174]]),
 array([[0.01951311]]),
 array([[0.14372206]]),
 ar

In [53]:
#getting the job id's of the recommendations
top = sorted(range(len(output2)), key=lambda i: output2[i], reverse=True)[:3]
top
recommendation = pd.DataFrame(columns = ['CandidateID', 'JobID'])
count = 0
for i in top:
    recommendation.loc[count, 'CandidateID']=u
    recommendation.loc[count,'JobID']=final_all['job_id'][i]
    count += 1

In [54]:
recommendation

CandidateID                                 JobID
0  bc4d77ca-a201-4a84-a954-99fbd99c58c9  36665e8a-8dd2-402e-bcd4-5e0886a8f506
1  bc4d77ca-a201-4a84-a954-99fbd99c58c9  f0b43bed-662c-4a42-ac3e-31abd307094b
2  bc4d77ca-a201-4a84-a954-99fbd99c58c9  589c4e63-7e33-40c6-982e-26bba770d81a

In [69]:
#getting the job ids and their data
nearestjobs = recommendation['JobID'][:10]
job_description = pd.DataFrame(columns = ['JobID','text'])
for i in nearestjobs:
    index = np.where(final_all['job_id'] == i)[0][0]    
    job_description.loc[count, 'CandidateID']=u
    job_description.loc[count, 'JobID']=i
    job_description.loc[count, 'text']= final_all['text'][index]
    count += 1
    


In [70]:
#printing the jobs that matched the query
job_description

JobID  \
12  36665e8a-8dd2-402e-bcd4-5e0886a8f506   
13  f0b43bed-662c-4a42-ac3e-31abd307094b   
14  589c4e63-7e33-40c6-982e-26bba770d81a   

                                              text  \
12     mechnic fitter iti raipur apprentic fresher   
13           mine diploma kurnool contractu 3 5 yr   
14  draughtsman diploma ghaziabad full time 0 2 yr   

                             CandidateID  
12  bc4d77ca-a201-4a84-a954-99fbd99c58c9  
13  bc4d77ca-a201-4a84-a954-99fbd99c58c9  
14  bc4d77ca-a201-4a84-a954-99fbd99c58c9